name: ai-server
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - fastapi==0.115.6
      - uvicorn==0.34.0
      - httpx==0.28.1
      - python-dotenv==1.0.1
      - pydantic==2.10.4
      - requests==2.32.3
